name: CI de Automatización de API

on:
  push:
    branches: [ "main" , "features/*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    name: Ejecutar Pruebas de Karate
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Otorgar permisos de ejecución a gradlew
        if: runner.os == 'Linux'
        run: chmod +x ./gradlew

      - name: Ejecutar Pruebas y Generar Reporte
        # La opción --continue asegura que todas las pruebas se ejecuten y los reportes se generen incluso si hay fallos.
        run: ./gradlew generateKarateReport --continue

      - name: Subir Reportes de Karate
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-reports-${{ matrix.os }}
          path: |
            build/karate-reports/
            build/cucumber-html-reports/
            target/
          if-no-files-found: ignore

